### PR TITLE
List only changes

### PR DESCRIPTION
**Pull request by basti1302**
Update: I removed the new command `changes-short` that had been introduced with this PR earlier and just changed the git command for `changes`. I also fixed all tests (unit and integeration).

TL;DR: This PR makes the output for `repoman changes` much shorter. See the examples below for comparison.

----

As discussed in #16, I'd like to get a terser list of local changes.

In this PR, I changed the git command for `repoman changes` to
```
git status -s && git log --branches --not --remotes --oneline
```
(the git log part obviously following you're clever suggestion from #16)

This makes it quite a bit terser already.

I also would like to get rid of echoing the executed commands to make the output even shorter, they have no benefit for me in day-to-day use. From your comments at #8 I understand this is more for debugging. So I went ahead and added a `verbose` option. I was feeling bold and made it default to `false`, so executed commands are only echoed if you explicitly specify `--verbose`, otherwise they are omitted.

One more minor thing: The regex for printing multiple commands ate everything except the last command, I fixed that.

What do you think?

----

For an example, here is the output of `repoman changes` for my current project, without my changes:

```
+ acceptance-tests-common
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ acceptance-tests-dairynet-dataprovider
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ acceptance-tests-dairynet-ui
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ acceptance-tests-gealibs
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ acceptance-tests-gealibs-dataprovider
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ bin
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ box-project-package
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-angular
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-backend
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-dataprovider
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-dp-import
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-fn-liquibase-addon
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-frontend
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/main/webapp/modules.json

no changes added to commit (use "git add" and/or "git commit -a")
[39m
+ dairynet-milking
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-presentation-layer
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-project-pom
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dairynet-setup
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dev-dairynet-box-setup
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dev-dairynet-time-machine
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dev-deployment
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ dev-documents
> git status
[32mOn branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean
[39m
+ dev-tools
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ gea-automation-dataprovider
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ gea-automation-domain
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ gea-automation-war
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ generator-model
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ generator-templates
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
+ qview-frontend
> git status
[32mOn branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[39m
```

----

Oh my gosh, that's a lot of output to process. I find it really hard to see at a glance if there is anything that still needs to be committed or pushed.

Here is the output of `repoman changes` after this changes:

----

```
+ acceptance-tests-common

+ acceptance-tests-dairynet-dataprovider

+ acceptance-tests-dairynet-ui

+ acceptance-tests-gealibs

+ acceptance-tests-gealibs-dataprovider

+ bin

+ box-project-package

+ dairynet-angular

+ dairynet-backend

+ dairynet-dataprovider

+ dairynet-dp-import

+ dairynet-fn-liquibase-addon

+ dairynet-frontend
[32m M src/main/webapp/modules.json
[39m
+ dairynet-milking

+ dairynet-presentation-layer

+ dairynet-project-pom

+ dairynet-setup

+ dev-dairynet-box-setup

+ dev-dairynet-time-machine

+ dev-deployment

+ dev-documents
[32m M .gitignore
[39m[32m30b6847 .
[39m
+ dev-tools

+ gea-automation-dataprovider

+ gea-automation-domain

+ gea-automation-war

+ generator-model

+ generator-templates

+ qview-frontend
```
Ah, much better. It only lists the project names and changes.

In an ideal world, I would like to have this output:

```
+ dairynet-frontend
[32m M src/main/webapp/modules.json
[39m
+ dev-documents
[32m M .gitignore
[39m[32m30b6847 .
[39m
```

That is, only list project with changes and omit projects without changes entirely. But this would probably require more changes in repoman logic and the current output is good enough.

### CODE REVIEW

**Comment by basti1302** [comment]
If you are fine with this changes I could squash the commits, I think it's ready to merge.

**Comment by basti1302** [comment]
Bump? :wink:

**Comment by basti1302** [comment]
Trying to summon @cliffano once again...

**Comment by cliffano** [comment]
Hi @basti1302 ,

Would you be interested in taking over the maintenance of repoman?
I'm struggling to find free time to work on repoman, and I think it will improve better in your hand.

Here's what I'm proposing:
1. I'll add you as the owner of repoman package on npm
2. Your fork will become the true source of repoman (feel free to update the URLs in package.json etc to point to your fork)
3. I'll update my repoman README with a note and a link to your fork page

Let me know what you think.

**Comment by basti1302** [comment]
Hey @cliffano, yes, I could do that. Your plan sounds good. Thanks for the offer.

**Comment by basti1302** [comment]
On second though, it might be better to use the GitHub functionality to transfer repositories:

https://github.com/cliffano/repoman/settings -> Danger Zone -> Transfer ownership 

I'll discard my fork for now. Otherwise the repo would always show up as a fork of your original repo, leading to confusion.

**Comment by cliffano** [comment]
@basti1302  I've sent the transfer request.

**Comment by basti1302** [comment]
Now the only thing missing is the npm part, that is `npm owner add basti1302 repoman`.

Thanks!

**Comment by cliffano** [comment]
Done.

Thanks for taking over the maintenance of repoman.
Please feel free to update the site URLs, doco, build tools etc. (I wrote bob back in node v0.2 days, way before grunt, gulp, etc)

Looking forward to the future improvements!

**Comment by basti1302** [comment]
These changes have been merged now.

**Pull request closed without merging**
