### PR TITLE
support 2FA for Github by adding sign in method to store oauth token in dotfile

### PR DESCRIPTION
**Pull request by scamden**
this was my hack. obviously you would need to either store or delete the token. but maybe this can help. i wasn't sure where you would consider storing auth info.

### CODE REVIEW

**Comment by basti1302** [comment]
Hi there, 

what is your intention here? Do plan to extend this commit into a clean solution or do you expect me to take your hack and polish it? To be honest, the latter will not happen. I would be willing to help you with the first, though.

As it stands, the PR can not be merged for a number of reasons:

* as you said, it is more a hack than a proper solution
* it breaks existing tests
* it does not come with new tests covering the use of the new parameter you introduced
* it lacks documentation for the new parameter
* the diff is not clean - seems you edited the files with an editor that does some kind of automatic formatting, resulting in a lot of formatting changes in places where you did not do a real code change. Please respect the existing code formatting style.

If you are willing to clean this up, I'm sure we can get it in.

**Comment by scamden** [comment]
@basti1302 my intention was simply to have a place for conversation about this. i guess i was hoping you might be interested in finishing the pr to fix the issue I filed since not having 2fa is a major blocker to many github users, but i'm open to helping if not. my thoughts for a better solution were to add a `signIn` method to repoman, that would follow this auth process and then store the token somewhere like ~/.repomanrc similar to how npm does. my concern was that i wasn't sure if that's how you'd prefer to store it, and wondered if you have thoughts for what to do cross platform as well. if you had a better thought than the sign in approach, i'd love to hear that as well.

also apologies for the formatting. i do have jsformat installed and running on save, but if we agree on a good approach to move forward with i'll probably just reset and start again, and i'll turn it off. out of curiosity do you have a formatting tool that you use with this code?

**Comment by scamden** [comment]
@basti1302 what do you think? if this is a decent approach in your book i'll start working on it

**Comment by basti1302** [comment]
Sorry for the late reply. I think the `sign-in` command that stores the token in a dot file in the user's home would work. It should be possible to get the user's home in a cross platform compatible way, for example via [process.env.HOME](https://nodejs.org/api/all.html#process_process_env), see also http://stackoverflow.com/questions/19275776/node-js-how-to-get-the-os-platforms-user-data-folder
I bet there's even a helpful npm module around, maybe something like [dotfile](https://www.npmjs.com/package/dotfile) would make that part easier.

The other methods accessing github would then check if the dotfile with the token is there, if it exists, use it, if not, not.

How does that sound?

**Comment by scamden** [comment]
that sounds awesome! sorry for my late reply as well haha. as soon as i get a chunk of free time i'll look into this approach! if we're going to use a dotfile we could also start storing defaults for some of repoman's options which would also be cool!

**Comment by scamden** [comment]
@basti1302 sorry for the long delay man! started a new job and have been suuuuper busy. i think this is in a pretty nice state now and fixed the major formatting issues. let me know what you think!

**Comment by scamden** [comment]
looks like there are some test failures. i'll fix those

**Comment by scamden** [comment]
ok finally fixed the tests and added one for the new auth method. @basti1302 let me know if you can merge

**Comment by basti1302** [comment]
This is not a small change, so I need some time to review it. I can probably take a closer look at the end of next week.

**Comment by scamden** [comment]
sounds good :) thanks for taking the time

**Comment by basti1302** [comment]
This has been merged now and landed in release 1.2.0. Sorry it took a bit longer.

**Comment by scamden** [comment]
No problem! Thanks for reviewing!

**Pull request closed without merging**
