### PR TITLE
use mock-fs for file-system tests

### PR DESCRIPTION
**Pull request by andreashouben**
I used mock-fs to mock the local filesystem. This way the tests for local.js can run on Windows.

Unfortunately there are still some tests failing under windows :(

### CODE REVIEW

**Comment by basti1302** [comment]
LGTM, thanks 🙇 

Two questions: 

1) Out of curiosity: What problem with the tests on Windows does that solve exactly? As far as I can tell, the file system access had been mocked before via Sinon? This is really just me being curious, the introduction of mock-fs is a change for the better anyway, I think.

2) Do you plan to add more to this PR? (for example, for other failing tests on Windows) Or do you intend to land this as-is, potentially adding other changes later via separate PRs? (I'm fine with both.)

**Comment by basti1302** [comment]
For the record, for some reason, this fails reproducible on Travis with

```
Command get should update repositories
test-integration/success-config-file.yml
../../../../../bin/repoman --config-file ../../../../../test-integration/fixtures/.somerepoman_success.json get
Output does not match expected regexp 'Current branch master is up to date.'
----------------
Command get should update repositories
test-integration/success.yml
../../../../../bin/repoman get
Output does not match expected regexp 'Current branch master is up to date.'
26 tests, 24 successes, 2 failures
```

The branch builds successfully for me locally. Unfortunately the test tool used in this project (`cmdt`) does not print the actual result it got from executing the command, it only prints its expectation 🤦

**Comment by andreashouben** [comment]
1. The problem was with the path.join method. On windows it produces something like 'repo\.git\config' which doesn't match against the value 'repo/.git/config' expected by Sinon.
2. I guess I'll file a new pull requests for other failing test that I fixed. Baby steps :baby: 

It's interesting that the integration test fails, because I changing nothing in the production code...

**Comment by basti1302** [comment]
re: path.join: yup, that makes sense.

Regarding the integration test failures: I'm 99% sure that these failures are totally unrelated to your changes.

**Comment by basti1302** [comment]
Regarding the test failure: I patched the test tool (cmdt, see https://github.com/cliffano/cmdt/pull/11) and now the root cause for the failure is very obvious (and of course unrelated to the changes in this PR): 

https://travis-ci.org/github/basti1302/repoman/jobs/738901859

```
Command get should update repositories
test-integration/success-config-file.yml
../../../../../bin/repoman --config-file ../../../../../test-integration/fixtures/.somerepoman_success.json get
Output: '
+ datagen
warning: redirecting to https://github.com/cliffano/datagen/
Already up to date.
+ nestor
warning: redirecting to https://github.com/cliffano/nestor/
Already up to date.
' does not match expected regexp 'Current branch master is up to date.'
----------------
Command get should update repositories
test-integration/success.yml
../../../../../bin/repoman get
Output: '
+ datagen
warning: redirecting to https://github.com/cliffano/datagen/
Already up to date.
+ nestor
warning: redirecting to https://github.com/cliffano/nestor/
Already up to date.
' does not match expected regexp 'Current branch master is up to date.'
26 tests, 24 successes, 2 failures
```

**Comment by basti1302** [comment]
it's fixed now

**Pull request merged**
